const boats = [
  {
    boatName: "joao",
    type: "yatch",
    guestMax: 20,
    guestMin: 5,
    size: "20 meters",
    descreiption: "beautifull boat for sunset trips",
  },
  {
    boatName: "tiago",
    type: "sail boat",
    guestMax: 110,
    guestMin: 70,
    size: "18 meters",
    descreiption: "amazing and cozy",
  },
  {
    boatName: "mariana",
    type: "catamaram",
    guestMax: 25,
    guestMin: 9,
    size: "40 meters",
    descreiption: "right for all the family",
  },
  {
    boatName: "angela",
    type: "fishin boat",
    guestMax: 45,
    guestMin: 11,
    size: "33 meters",
    descreiption: "big and luxury",
  },
  {
    boatName: "oliver",
    type: "yatch",
    guestMax: 210,
    guestMin: 55,
    size: "23 meters",
    descreiption: "we accept pets",
  },
  {
    boatName: "charlotte",
    type: "catamaram",
    guestMax: 34,
    guestMin: 20,
    size: "8 meters",
    descreiption: "ready for overnight trips",
  },
  {
    boatName: "roberto",
    type: "sail boat",
    guestMax: 23,
    guestMin: 5,
    size: "43 meters",
    descreiption: "for the party animals",
  },
  {
    boatName: "paulino",
    type: "fishing boat",
    guestMax: 65,
    guestMin: 7,
    size: "12 meters",
    descreiption: "weddings and events available",
  },
  {
    boatName: "amilton",
    type: "yatch",
    guestMax: 76,
    guestMin: 23,
    size: "9 meters",
    descreiption: "share with friends and family",
  },
  {
    boatName: "rodrigo",
    type: "catamaram",
    guestMax: 65,
    guestMin: 15,
    size: "21 meters",
    descreiption: "get away and enjoy the sea",
  },
  {
    boatName: "jorge",
    type: "sail boat",
    guestMax: 240,
    guestMin: 34,
    size: "33 meters",
    descreiption: "the best for you and a good price",
  },
  {
    boatName: "carlos",
    type: "fishing boat",
    guestMax: 23,
    guestMin: 3,
    size: "3 meters",
    descreiption: "lets conquer the 7 seas",
  },
];
